// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OnlineRepository {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button DiamondSquareAlgorithm;
		
		protected System.Web.UI.WebControls.Button RaisingHighMaps;
		
		protected System.Web.UI.WebControls.Button PotentialEnergy;
		
		protected System.Web.UI.WebControls.Button PotentialEnergyColored;
		
		protected System.Web.UI.WebControls.Button FireEffect;
		
		protected System.Web.UI.WebControls.Button Pixelation;
		
		protected System.Web.UI.WebControls.Button RotatePalette;
	}
}
