// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OnlineRepository {
	
	
	public partial class DiamondSquareAlgorithm {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.TextBox tbEntrophy;
		
		protected System.Web.UI.WebControls.DropDownList ddPalette;
		
		protected System.Web.UI.UpdatePanel UpdatePanel1;
		
		protected System.Web.UI.WebControls.Button btGenerate;
		
		protected System.Web.UI.WebControls.Label InfoLabel;
		
		protected System.Web.UI.WebControls.Image UHighMap;
	}
}
