// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OnlineRepository {
	
	
	public partial class FireEffect {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl PageBody;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.UpdatePanel UpdatePanel1;
		
		protected System.Web.UI.WebControls.Button btRandomPalette;
		
		protected System.Web.UI.WebControls.Button btDefaultPalette;
		
		protected System.Web.UI.Timer Timer;
		
		protected System.Web.UI.WebControls.Label InfoLabel;
		
		protected System.Web.UI.WebControls.Image UImage;
	}
}
